name: Test Workflow

on:
  push:
    branches:
      - master  # أو غيريها للفرع اللي عندك فعلياً

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Testing GITHUB
        run: pwd

      - name: Printing folder contents
        run: ls
