name: Test Workflow

on:
  push:
    branches:
      - master  # أو غيريها للفرع اللي عندك فعلياً

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Testing GITHUB
        run: pwd

      - name: before
        run: ls
      - ueses: actions/checkout@v3
      - name : after
        run: ls