name: Test Workflow

on:
  push:
    branches:
      - master  # أو غيريها للفرع اللي عندك فعلياً

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Testing GITHUB
        run: pwd

      - name: before
        run: ls

      - uses: actions/checkout@v3

      - name: after
        run: ls

      
      - name: Docker login
        run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_TOKEN }}



