name: Test Workflow

on:
  push:
    branches:
      - master  # أو غيريها للفرع اللي عندك فعلياً

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Testing GITHUB
        run: pwd

      - name: before
        run: ls
      - uses: actions/checkout@v3
      - name : after
        run: ls
        -name: login
        run: docker login --username Malk Osama --password dckr_pat__D93EKR2ns0mwu0Gq9O2oDV3Zak  