name: Test Workflow

on:
  push:
    branches:
      - master  # أو غيريها للفرع اللي عندك فعلياً

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - uses: actions/checkout@v3

      # 2️⃣ Docker login
      - name: Docker login
        run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_TOKEN }}

      # 3️⃣ Build Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/malak2023040259

      # 4️⃣ Push Docker image
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/malak2023040259
